import { createSlice } from "@reduxjs/toolkit"

// Define the initial state for the cart
const initialState = []

// Create a cart slice using createSlice function
const cartSlice = createSlice({
  name: "cart", // Specify the name of the slice
  initialState, // Set the initial state for the cart
  reducers: {
    // Define the "add" action
    add(state, action) {
      // Mutate the state by pushing the payload to the cart array
      state.push(action.payload)
    },
    // Define the "remove" action
    remove(state, action) {
      // Return a new state by filtering out the item with the given ID
      return state.filter((item) => item.id !== action.payload)
    },
  },
})

// Export the "add" and "remove" actions from the cartSlice.actions object
export const { add, remove } = cartSlice.actions

// Export the reducer function generated by createSlice as the default export
export default cartSlice.reducer
